name = "hono-oath2-admin-api"
main = "src/index.ts"
compatibility_date = "2024-12-17"
assets = { directory = "public" }

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "OAUTHABL"
id = "062715e6f04e4bcabd6f372589a52a32"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability.logs]
enabled = true
# head_sampling_rate = 1