name = "hono-oath2-admin-api"
main = "src/index.ts"
compatibility_date = "2024-12-17"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "OUATHABL"
id = "2e912562ac3f4f999093552b063d9cc3"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1