name = "hono-oath2-admin-api"
main = "src/index.ts"
compatibility_date = "2024-12-17"
assets = { directory = "public" }

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "dbf8308bccfd4b80936211bed77a2ac7"

[[r2_buckets]]
binding = "R2"
bucket_name = "oauthabl"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability.logs]
enabled = true
# head_sampling_rate = 1